title: CSUN Inclusive Description Guidelines
description: These guidelines are meant to provide guidance and clarity in the creation of inclusive descriptions for archival materials in finding aids and digital collections metadata. 
theme: just-the-docs

url: https://nlshibata.github.io/csun-inclusive-description

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
